microsoft/accessibility-insights-for-android-service

- AccessibilityInsightsForAndroidService/.idea/codeStyles/Project.xml
- AccessibilityInsightsForAndroidService/.idea/gradle.xml
- AccessibilityInsightsForAndroidService/app/build.gradle
- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/ServerSocketFactory.java
Validated with emulated device on OS 26 and OS 24.
> fix: use get localhost instead of loopback address

- pipeline/release-build.yaml
Currently, no part of our build or release pipeline signs the APK. This PR introduces the ESRP CodeSign task to release-build.yaml to sign our APK. This will allow us to download the APK from the build artifact for testing purposes and to consume said APK in the release pipeline. You can find a [signed apk in the artifacts here](https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_build/results?buildId=10031&view=results). I verified that the cert of the newly published APK matches the cert of our previously published APK using `keytool -list -printcert -jarfile <apk>`.
- [n/a] Ran `./gradlew fastpass` from `AccessibilityInsightsForAndroidService`
> fix: Sign APK during release build using ESRP CodeSign

- pipeline/infer-version-code-from-version-name.js
- pipeline/release-build.yaml
This PR is a preventative measure to avoid the class of issue described by #21; it removes the human step of specifying an APK_VERSION_CODE from our release process by having the build infer it automatically from APK_VERSION_NAME.
Once this PR is merged, I'll update the release validation template accordingly.
Out of scope for this PR: implementing the logic #21 suggests for validating that versionName is newer than all previous releases.
I verified manually that all of the error paths catch the issues that they're supposed to.
[Example build with successful APK_VERSION_CODE inference](https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_build/results?buildId=11257&view=results) (you can verify that the correct versionCode is applied by examining the …
> fix(release-build): prevent future mismatches of versionName and versionCode

- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/ImageFormatException.java
- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/OnScreenshotAvailable.java
- AccessibilityInsightsForAndroidService/app/src/test/java/com/microsoft/accessibilityinsightsforandroidservice/OnScreenshotAvailableTest.java
This fixes the issue described by #19 by detecting the case where the system has provided an image data with row padding and creating an intermediate, unpadded image buffer before invoking `Bitmap::copyPixelsFromBuffer`.
I explored a few other implementation options in the hopes of avoiding having to allocate the intermediate buffer, but they all came up short because `copyPixelsFromBuffer` is the only method `Bitmap` exposes that copies the backing data *exactly as-is* from the original source data, without applying any color transformations on the data. In particular, the variants of `Bitmap::createBitmap` and `Bitmap::setPixels` that accept `int[] colors` parameters look promising because some of them have built-in support for explicit `stride` parameters, but all of them perform color …
> fix: avoid extra padding in screenshots on devices that use row-padded images

- npm-wrapper/README.md
* Clarify that the wrapper is a CommonJS module
* Clarify that the usage example is for typescript (the import syntax is a little different in js)
* Clarify that it exports the version, not just the paths
* Clarify gotcha about `__dirname` usage that Dave noted
- [n/a] Ran `./gradlew fastpass` from `AccessibilityInsightsForAndroidService`
> chore: update wrapper README per feedback from 1.2.0 validation

- pipeline/release-build.yaml
#34 updated our android build tools, and apparently the updated build tools now write release variable metadata into `output-metadata.json` where they previously used `output.json`. This broke a build task we have to print that file for debugging purposes.
> chore: fix release build to accomodate updated release output filename

- AccessibilityInsightsForAndroidService/app/build.gradle
- AccessibilityInsightsForAndroidService/app/gradle.lockfile
This cleans up some outdated bits of build.gradle's `dependencies` block:
* Removes obsolete commented dependency
* Updates `androidTestImplementation` to use the more current `androidx` version rather than the deprecated `com.android.support` equivalent (this has the side effect of updating the lockfile to use stable rather than alpha versions of some testing libraries)
* Clarifies dev vs non-dev dependencies
* Sort lines
> chore(dev-deps): Clean up deps listings in build.gradle

- AccessibilityInsightsForAndroidService/gradlew.bat
When trying to run **gradlew fastpass**, I hit an error that JAVA_HOME wasn't set. That set me trying to figure out what was missing, and it turns out that java is installed as part of Android Studio, so nothing else needed to be done. This change adds an extra check to the initialization code and allows the default Android Studio location to be used. This seemed like a simpler approach than trying to tell people to download and install the JDK, since the JDK download process requires creating an account and may introduce licensing issues.
Output if JAVA_HOME _can't_ be inferred from default Android Studio install:
```
>gradlew fastpass
WARNING: JAVA_HOME is not set and no 'java' command could be found in your PATH.
Attempting to infer JAVA_HOME based on a default Android Studio …
```
> chore: Infer JAVA_HOME from default Android Studio install

- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/NodeViewBuilder.java
- AccessibilityInsightsForAndroidService/app/src/test/java/com/microsoft/accessibilityinsightsforandroidservice/NodeViewBuilderTest.java
The axe-android code will throw an exception if className is null (see https://github.com/dequelabs/axe-android/issues/127 for details). For now, prevent that from happening by replacing the null value with a synthetic value that is clearly ours.
> fix: Add null class name workaround

- AccessibilityInsightsForAndroidService/build.gradle
This PR prevents a type of supply-chain substitution attack. Previously, for libraries which our build gets from Google's maven repository, our build first checks the maven repository provided by `jcenter()` for each library in question, and falls back to Google's in the event that it doesn't exist in `jcenter()`. If a malicious actor were to register one of those libraries' names on `jcenter()`, we would end up incorrectly using that version instead of the version from Google's Maven repository. With this PR, we direct Gradle to *only* look in the `google()` Maven repository for those libraries which we expect to come from there (and vice-versa).
The repetition between the `buildscript` and `allprojects` sections is undesirable, but I wasn't able to find a way to avoid it; Gradle …
> chore(deps): specify Google Maven as the exclusive provider of its deps

- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/AccessibilityEventDispatcher.java
- AccessibilityInsightsForAndroidService/app/src/test/java/com/microsoft/accessibilityinsightsforandroidservice/AccessibilityEventDispatcherTest.java
Creates a class to be utilized later in the "onAccessibilityEvent" hook in the service.
The tabstops feature requires us to listen to event types for accessibility events. This allows a specific place for that.
I decided to go with an array of listeners because I figured it wasn't much more work to do so now and also this may allow us to break apart future components a bit more easily.
> feat(focus-mvp-android-client): create Accessiblity Event Dispatcher

- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/Command.java
- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/FocusVisualizationStateManager.java
- AccessibilityInsightsForAndroidService/app/src/test/java/com/microsoft/accessibilityinsightsforandroidservice/FocusVisualizationStateManagerTest.java
Adds a place to manage the state for the focus visualization.
For tab stops feature.
Does not include usage.
Command is a functional interface like Consumer but takes no arguments.
> feat(focus-mvp-android-device): add focus visualization state manager

- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/FocusVisualizerController.java
- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/LayoutParamGenerator.java
- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/UIThreadRunner.java
- AccessibilityInsightsForAndroidService/app/src/test/java/com/microsoft/accessibilityinsightsforandroidservice/FocusVisualizerControllerTest.java
- AccessibilityInsightsForAndroidService/app/src/test/java/com/microsoft/accessibilityinsightsforandroidservice/LayoutParamGeneratorTest.java
- AccessibilityInsightsForAndroidService/app/src/test/java/com/microsoft/accessibilityinsightsforandroidservice/UIThreadRunnerTest.java
Adds focus visualizer controller which should manage when to pass on focus/redraw events and other such aspects of the focus visualization.
Feature work
Does not include wiring up.
> feat(focus-mvp-android-device): add focus visualizer controller + related classes

- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/AccessibilityEventDispatcher.java
We meant to remove TYPE_WINDOW_CONTENT_CHANGED but accidentally removed TYPE_WINDOW_STATE_CHANGED from the redraw events in a previous PR.
> feat(focus-mvp-android-device): fix redraw event types

- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/AccessibilityEventDispatcher.java
- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/FocusElementHighlight.java
- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/FocusElementLine.java
- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/FocusVisualizer.java
- AccessibilityInsightsForAndroidService/app/src/test/java/com/microsoft/accessibilityinsightsforandroidservice/AccessibilityEventDispatcherTest.java
- AccessibilityInsightsForAndroidService/app/src/test/java/com/microsoft/accessibilityinsightsforandroidservice/FocusElementHighlightTest.java
- AccessibilityInsightsForAndroidService/app/src/test/java/com/microsoft/accessibilityinsightsforandroidservice/FocusElementLineTest.java
- AccessibilityInsightsForAndroidService/app/src/test/java/com/microsoft/accessibilityinsightsforandroidservice/FocusVisualizerTest.java
This uses the refresh method inside the draw method to determine whether it should draw anything at all (refresh returns false when element is not visible/on screen).
feature work.
> feat(focus-mvp-android-device): updates visualizations when elements are not present

- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/FocusVisualizer.java
- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/FocusVisualizerController.java
- AccessibilityInsightsForAndroidService/app/src/test/java/com/microsoft/accessibilityinsightsforandroidservice/FocusVisualizerControllerTest.java
- AccessibilityInsightsForAndroidService/app/src/test/java/com/microsoft/accessibilityinsightsforandroidservice/FocusVisualizerTest.java
Keeps track of the last event source to then use for highlighting when focus visualization is enabled.
feature work
Changed some interactions between classes since we cannot store the AccessibilityEvent but can store the AccessibilityNodeInfo underlying it.
> feat(focus-mvp-android-device): last focused node is highlighted when focus visualization enabled

- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/FocusElementHighlight.java
- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/FocusVisualizer.java
- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/FocusVisualizerStyles.java
- AccessibilityInsightsForAndroidService/app/src/test/java/com/microsoft/accessibilityinsightsforandroidservice/FocusElementHighlightTest.java
- AccessibilityInsightsForAndroidService/app/src/test/java/com/microsoft/accessibilityinsightsforandroidservice/FocusVisualizerStylesTest.java
This moves the visualization of the current focus element highlight in line with the spec, by ensuring that the inner circle is transparent.
Fixes current element highlight inner-circle transparency
> feat(focus-mvp-android-device): current focus element highlight transparent inner circle

- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/AccessibilityInsightsForAndroidService.java
- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/DateProvider.java
- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/FocusVisualizerController.java
- AccessibilityInsightsForAndroidService/app/src/test/java/com/microsoft/accessibilityinsightsforandroidservice/FocusVisualizerControllerTest.java
Will ignore focus events for focus visualization purposes after orientation has been changed for 1 second.
feature work.
Using a new class known as Date Provider, a pattern we've used before, so that I don't have to use static mocks which are a bit troublesome.
> feat(focus-mvp-android-device): silence focus events after a recent orientation change

- AccessibilityInsightsForAndroidService/build.gradle
This PR changes which repository we download most dependencies on from JCenter ([which is being shut down on May 1 2021](https://developer.android.com/studio/build/jcenter-migration)) to Maven Central.
There is one dependency (`org.jetbrains.trove4j:trove4j`) which is present on JCenter but not Maven Central (see [these](https://stackoverflow.com/q/49573157/2825668) [two](https://stackoverflow.com/q/45818613/2825668) StackOverflow threads). [Based on those threads](https://stackoverflow.com/a/66168563/2825668), the most reputable location where this dependency is published appears to be the Gradle Plugins repository, which in Gradle 6 is officially aliased as `gradlePluginPortal()`.
See #70 for context on why we use an `exclusiveContent` directive for this for this, rather than just a …
> chore: replace jcenter with mavenCentral

- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/RequestHandlerFactory.java
- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/ResponseThreadFactory.java
- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/ResultRequestFulfiller.java
- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/ResultSerializer.java
- AccessibilityInsightsForAndroidService/app/src/test/java/com/microsoft/accessibilityinsightsforandroidservice/RequestHandlerFactoryTest.java
- AccessibilityInsightsForAndroidService/app/src/test/java/com/microsoft/accessibilityinsightsforandroidservice/ResultRequestFulfillerTest.java
- AccessibilityInsightsForAndroidService/app/src/test/java/com/microsoft/accessibilityinsightsforandroidservice/ResultSerializerTest.java
In preparation for adding ATFA results, this PR introduces `ResultSerializer` and uses it to generate the response string in `ResultRequestFulfiller`. This has no functional impact--for now, `ResultSerializer` is just a wrapper around `AxeResult` that calls `toJson()`.
Ultimately, we need a way to return AxeResults, ATFA results, and ATFA rules serialized alongside each other. This PR introduces the layer of abstraction where this serialization will take place.
Out of scope: adding any new results to the response of `ResultRequestFulfiller`. Future PRs will expand upon `ResultSerializer` such that it returns additional data.
> feat(google-rules-mvp-service): Introduce ResultSerializer and use in ResultRequestFulfiller

- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/ATFAScanner.java
- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/ATFAScannerFactory.java
- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/AccessibilityInsightsForAndroidService.java
- AccessibilityInsightsForAndroidService/app/src/test/java/com/microsoft/accessibilityinsightsforandroidservice/ATFAScannerFactoryTest.java
- AccessibilityInsightsForAndroidService/app/src/test/java/com/microsoft/accessibilityinsightsforandroidservice/ATFAScannerTest.java
This PR creates the ATFAScanner, which uses the [Accessibility Test Framework for Android](https://github.com/google/Accessibility-Test-Framework-for-Android), and the ATFAScannerFactory. Like the existing AxeScanner, the ATFAScanner runs the rules (ATFA instead of axe, in this case) on a given root node and then returns the results. 
This is a part of the feature to add ATFA to AI for Android Service.
Created an instance of ATFAScanner in AccessibilityInsightsForAndroidService.java, but adding it to the ResponseThreadFactory and RequestHandlerFactory will be done in a future PR, most likely when updating the API.
It also filters the results to return only those with type ERROR, INFO, WARNING, RESOLVED, and NOT_RUN. This can be changed in the future, if we decide that we want to return …
> feat(google-rules-mvp-service): Create ATFAScanner

- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/AccessibilityInsightsForAndroidService.java
- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/RequestHandlerFactory.java
- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/ResponseThreadFactory.java
- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/ResultRequestFulfiller.java
- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/ResultSerializer.java
- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/ResultsContainer.java
- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/ResultsContainerSerializer.java
- AccessibilityInsightsForAndroidService/app/src/test/java/com/microsoft/accessibilityinsightsforandroidservice/RequestHandlerFactoryTest.java
- AccessibilityInsightsForAndroidService/app/src/test/java/com/microsoft/accessibilityinsightsforandroidservice/ResultRequestFulfillerTest.java
- AccessibilityInsightsForAndroidService/app/src/test/java/com/microsoft/accessibilityinsightsforandroidservice/ResultSerializerTest.java
- AccessibilityInsightsForAndroidService/app/src/test/java/com/microsoft/accessibilityinsightsforandroidservice/ResultsContainerSerializerTest.java
Previous PRs introduced `ATFAScanner`, `ATFAResultSerializer`, and `ResultSerializer` (#104, #108, and #102). This PR puts them together to run, serialize, and return ATFA results. To accomplish this, `ResultsContainer` is introduced and `ResultSerializer` is refactored to serialize it. 
Now ATFA rules are run and results are returned!
A future PR will add ATFARules to the return object, as well. 
Note that these changes will require updates on the AI-Android client receiving end.
> feat(google-rules-mvp-service): Run, serialize, and return ATFA results

- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/ResponseThreadFactory.java
- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/ResultsContainerSerializer.java
- AccessibilityInsightsForAndroidService/app/src/test/java/com/microsoft/accessibilityinsightsforandroidservice/ResultsContainerSerializerTest.java
This adds the ATFARulesSerializer from #111 to the ResultsContainerSerializer from #102 and #110.
Part of feature 1833283
This is the last part needed to get the ResultsContainerSerializer to return a json with all the necessary data. 
The returned json is formatted like the following:
```
{ 
AxeResults: {...},
ATFARules: [...},
ATFAResults: [...]
}
```
> feat(google-rules-mvp-service): add ATFARulesSerializer to ResultsContainerSerializer

- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/ATFARulesSerializer.java
- AccessibilityInsightsForAndroidService/app/src/test/java/com/microsoft/accessibilityinsightsforandroidservice/ATFARulesSerializerTest.java
This PR causes the `Pattern` class to be excluded from ATFA rules serialization.
On Android versions prior to Android 9, the `Pattern` class cannot be serialized by the default Gson serializer. Thus, the [`Pattern` in `LinkPurposeUnclearCheck`](https://github.com/google/Accessibility-Test-Framework-for-Android/blob/master/src/main/java/com/google/android/apps/common/testing/accessibility/framework/checks/LinkPurposeUnclearCheck.java#L64) causes our serialization to fail on older Android versions.
Another option would be to implement a custom serializer for the `Pattern` class. We don't get anything interesting from `Pattern`, so we don't need to do that.
> fix: Exclude Pattern from ATFA rules serialization

- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/RequestHandlerFactory.java
- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/ResponseThreadFactory.java
- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/ResultV1RequestFulfiller.java
- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/ResultV1Serializer.java
- AccessibilityInsightsForAndroidService/app/src/test/java/com/microsoft/accessibilityinsightsforandroidservice/RequestHandlerFactoryTest.java
- AccessibilityInsightsForAndroidService/app/src/test/java/com/microsoft/accessibilityinsightsforandroidservice/ResultV1RequestFulfillerTest.java
- AccessibilityInsightsForAndroidService/app/src/test/java/com/microsoft/accessibilityinsightsforandroidservice/ResultV1SerializerTest.java
The results API was recently changed in a breaking way (the same API returns differently structured data), which will complicate development and E2E tests for the consuming code. To make our work easier, we've decided that the existing results API will return data in the original structure, and that the differently structured data will be returned through a new results_v2 API. Once we complete the migration of the consuming code, we'll drop the legacy version and support only the request_v2 API. The code in the "V1" classes here was removed in #110.
API change:
Version | Path
--- | ---
V1 (legacy) | `GET localhost://62442/AccessibilityInsights/result`
V2 (new) | `GET localhost://62442/AccessibilityInsights/result_v2`
This will make it a lot simpler to write E2E tests for the client.
There …
> chore: Support v1 and v2 versions of results API

- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/RequestHandlerFactory.java
- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/ResponseThreadFactory.java
- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/ResultV2RequestFulfiller.java
- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/ResultsV2Container.java
- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/ResultsV2ContainerSerializer.java
- AccessibilityInsightsForAndroidService/app/src/test/java/com/microsoft/accessibilityinsightsforandroidservice/RequestHandlerFactoryTest.java
- AccessibilityInsightsForAndroidService/app/src/test/java/com/microsoft/accessibilityinsightsforandroidservice/ResultV2RequestFulfillerTest.java
- AccessibilityInsightsForAndroidService/app/src/test/java/com/microsoft/accessibilityinsightsforandroidservice/ResultsV2ContainerSerializerTest.java
PR #115 included a follow-up to rename classes to reflect their usage in the `result_v2` API. This PR consists of the following:
- Rename `ResultRequestFulfiller` to `ResultV2RequestFulfiller`
- Rename `ResultRequestFulfillerTest` to `ResultV2RequestFulfillerTest`
- Rename `ResultsContainerSerializer` to `ResultsV2ContainerSerializer`
- Rename `ResultsContainerSerializerTest` to `ResultsV2ContainerSerializerTest`
- Update some variable names to better reflect the typing
- Include the result version in logging calls, update corresponding unit tests
This was a separate PR just to simplify reviewing and tracking the changes
- [n/a] Addresses an existing issue:
> chore: Complete class renames for result_v2 API

- pipeline/release-build.yaml
I just rotated the certificate used to authenticate our signing requests. While I was in the area I renamed the service connection reference. In general the rotation doesn't require code changes unless the name is changed.
I tested the new cert [here](https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_build/results?buildId=23962&view=results).
Renaming for clarity, finalizing rotation
> chore: update name of ESRP service connection after rotation

- AccessibilityInsightsForAndroidService/.idea/compiler.xml
- AccessibilityInsightsForAndroidService/.idea/misc.xml
- AccessibilityInsightsForAndroidService/.idea/runConfigurations.xml
- AccessibilityInsightsForAndroidService/app/build.gradle
- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/ATFARulesSerializer.java
- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/AxeRunnerFactory.java
- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/OnScreenshotAvailable.java
- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/OnScreenshotAvailableProvider.java
- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/ScreenshotController.java
- AccessibilityInsightsForAndroidService/app/src/test/java/com/microsoft/accessibilityinsightsforandroidservice/ATFAResultsSerializerTest.java
- AccessibilityInsightsForAndroidService/app/src/test/java/com/microsoft/accessibilityinsightsforandroidservice/ConfigRequestFulfillerTest.java
- AccessibilityInsightsForAndroidService/app/src/test/java/com/microsoft/accessibilityinsightsforandroidservice/OnScreenshotAvailableTest.java
- AccessibilityInsightsForAndroidService/app/src/test/java/com/microsoft/accessibilityinsightsforandroidservice/RequestReaderTest.java
- AccessibilityInsightsForAndroidService/app/src/test/java/com/microsoft/accessibilityinsightsforandroidservice/ResultV1RequestFulfillerTest.java
- AccessibilityInsightsForAndroidService/app/src/test/java/com/microsoft/accessibilityinsightsforandroidservice/ResultV2RequestFulfillerTest.java
- AccessibilityInsightsForAndroidService/app/src/test/java/com/microsoft/accessibilityinsightsforandroidservice/ScreenshotControllerTest.java
- AccessibilityInsightsForAndroidService/app/src/test/java/com/microsoft/accessibilityinsightsforandroidservice/ServerThreadTest.java
- pipeline/release-build.yaml
- pipeline/validation-build.yaml
Before this PR, build warnings and lint warnings were being emitted on stdout during builds, but weren't actually blocking the build from succeeding, so they were being ignored and just producing noise.
This PR enables build, test, and compiler warnings to show up as build failures and fixes most pre-existing warnings. This reduces several bits of noise during builds (eg, the "try rebuilding with -Xlint:deprecated" messages and the 6 lines of red WARNING text you get in Android Studio when running tests there).
I've also set up the build to upload a `lint-results` artifact containing lint results (which were previously produced but discarded)
Avoid noise, fix issues preemptively
I included the necessary `.idea` files to run from Android Studio 4.2.2 (latest stable) as part of the PR since …
> chore: make compiler/lint warnings fail the build

- AccessibilityInsightsForAndroidService/app/build.gradle
Our lint setup is intended to have "out of date dependency" lints like `GradleDependency` be listed as non-build-breaking warnings, not errors, so they don't block build reproducibility or unrelated PRs. However, we missed one type of lint in that class (`NewerVersionAvailable`) when we set up lint-errors-break-builds a few weeks ago. This PR updates the lint config to treat `NewerVersionAvailable` lint failures as warnings rather than errors.
Build reproducibility, unblock dependabot PRs #124  and #123 that are currently blocked on each other.
n/a
> chore: prevent NewerVersionAvailable lint from breaking the build

- AccessibilityInsightsForAndroidService/app/src/main/AndroidManifest.xml
- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/TempFileProvider.java
- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/WorkManagerHolder.java
As called out in #150, the current code fails to initialize on API 29 or higher. The root problem is that `WorkManager.initialize()` is not being called before the first call to `WorkManager.getInstance()`. If we simply force the call, it gets called by the default handler and fails in a different way. This PR does the following:
- Suppresses automation initialization of `WorkManager` via a manifest change
- Adds a wrapper (`WorkManagerHolder`) that ensures that we only initialize exactly once per `Context`. Since `Context` offers a `getHashCode()` method, we can safely use a `Context` as the key for a `HashMap`. It may be worth pointing out that this isn't thread-safe, but there's no indication that we need to worry about that scenario.
- Gets the `Context`-specific `WorkManager` object …
> fix: Explicitly manage WorkManager.initialize

- AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/WorkManagerHolder.java
#152 used a `HashMap` based on a `Context` object. This can have negative perf implications, so we're changing it to a `WeakHashMap`. We also synchronized calls into the `WorkManagerHolder` to avoid race conditions that would be hard to repro and/or debug.
Minimize perf impact, improve resiliency.
- [n/a] Addresses an existing issue:
> chore: Improve perf and reliability of WorkManagerHolder

- pipeline/release-build.yaml
Updates our release pipeline to use the latest current LTS version of node (16)
Validated locally by manually running the scripts used by our release pipeline:
* `pipeline/verify-clean-lockfile.js`
* `pipeline/infer-version-code-from-version-name.js`
* `pipeline/verify-notice-contents.js`
Keep dependencies up to date
n/a
- [n/a] Ran `./gradlew fastpass` from `AccessibilityInsightsForAndroidService`
> chore(deps-dev): migrate release infra scripts to node 16

- AccessibilityInsightsForAndroidService/cgmanifest.json
This pull request adds the JSON schema for `cgmanifest.json`.
A JSON schema helps you to ensure that your `cgmanifest.json` file is valid.
JSON schema validation is a build-in feature in most modern IDEs like Visual Studio and Visual Studio Code.
Most modern IDEs also provide code-completion for JSON schemas.
Most modern IDEs like Visual Studio and Visual Studio Code have a built-in feature to validate JSON files.
You can also use [this small script](https://github.com/JamieMagee/verify-cgmanifest) to validate your `cgmanifest.json` file.
Component Detection is able to read camel case and pascal case properties.
However, the JSON schema doesn't have a case-insensitive mode.
We therefore suggest camel case as it's the most common format for JSON.
To deserialize the `cgmanifest.json` file, …
> Add `$schema` to `cgmanifest.json`

- pipeline/release-build.yaml
This PR bumps `EsrpCodeSignign@2` as part of pre-release preparations. 
Fix broken `Artifact release` pipeline:
https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_build/results?buildId=40900&view=logs&j=ee97c5d1-e7c0-57b6-e379-76cd471b81bc&t=c8f01bc9-a8db-5eb4-2676-54c8249ded2b
> fix: Upgrading ESRP to fix broken release pipeline

- AccessibilityInsightsForAndroidService/app/src/test/java/com/microsoft/accessibilityinsightsforandroidservice/ATFAResultsSerializerTest.java
Due to https://github.com/mockito/mockito/issues/2860, Dependbot has been unable to update to any version of `mockito-inline` since version 4.6.1. The failed attempts are as follows:
Version | Failed PR
--- | ---
4.7.0 | #169 
4.8.0 | #174
4.8.1 | #176
4.9.0 | #182
4.11.0 | #198 
In response to https://github.com/mockito/mockito/issues/2860, a suggestion was made to use an `ArgumentCaptor` to capture the arguments and the `RETURNS_SELF` parameter for the builder. This PR makes that change, so we're now capturing arguments using the construct that is intended for that purpose. The mockito team has not committed to fixing this issue and may even be leaning toward not fixing it, since a more officially supported option exists to do what we're doing.
I've applied these changes locally to #198 …
> chore: Workaround for mockito #2860

- pipeline/verify-notice-contents.js
This PR fixes an issue I noticed while porting part of this build script to the web repo.
The specific line in question is a regex that's intended to parse the "Summary" element from a generated NOTICE.html file. These elements look like this:
```html
<summary>
org.jetbrains/annotations 15.0 - Apache-2.0
</summary>
```
The bug this PR fixes is that the part of the regex that's matching the license (in the above example, `Apache-2.0`) wasn't permissive enough to cover all license expressions used by packages in the web repo. In particular, some packages have complex license expressions that use interesting combinations of licenses, like this:
```html
<summary>
json-schema 0.4.0 - AFL-2.1 OR BSD-3-Clause OR (AFL-2.1 AND BSD-3-Clause)
</summary>
```
The regex previously got confused in these …
> chore: fix verify-notice-contents to allow for parens in license expressions
